PAL - final project/pal/comments/urls.py
from django.urls import path
from . import views

app_name = 'comments'

urlpatterns = [
    path('update-comment/<str:pk>/', views.update_comment, name='update-comment'),
    path('delete-comment/<str:pk>/', views.delete_comment, name='delete-comment'),
]

PAL - final project/pal/pal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls')),
    path('', include('comments.urls')),
    path('', include('user.urls')),
    path('admin/', admin.site.urls),
]

PAL - final project/pal/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
  path('', views.index, name='index'),
  path('post/<str:pk>/', views.post, name='post'),
  path('create-post/', views.create_post, name='create-post'),
  path('update-post/<str:pk>/', views.update_post, name='update-post'),
  path('delete-post/<str:pk>/', views.delete_post, name='delete-post'),
]

PAL - final project/pal/comments/models.py
from django.db import models
from posts.models import Post
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE

# Create your models here.

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE) # each Comment is related to a single User
    post = models.ForeignKey(Post, on_delete=CASCADE) # each Comment is related to a single Post
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.body

PAL - final project/pal/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import SET_NULL

# Create your models here.

class Topic(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Post(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    topic = models.ForeignKey(Topic, null=True, on_delete=SET_NULL) # each Post is related to a single Topic
    user = models.ForeignKey(User, null=True, on_delete=SET_NULL) # each Post is related to a single User
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
        

PAL - final project/pal/posts/forms.py
from django.forms import ModelForm
from posts.models import Post


class PostForm(ModelForm):
    
    class Meta:
        model = Post
        fields = ['name', 'description', 'topic',]

PAL - final project/pal/posts/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib import messages
from posts.forms import PostForm
from posts.models import Post, Topic
from comments.models import Comment

# Create your views here.

def index(request):

    if request.GET.get('q') == None:
        query = ''
    else:
        query = request.GET.get('q')

    topics = Topic.objects.all()
    posts = Post.objects.filter(
        Q(topic__name__icontains=query) |
        Q(name__icontains=query) |
        Q(description__icontains=query) |
        Q(comment__body__icontains=query) |
        Q(user__username__icontains=query)
    ).order_by('-created')

    posts_count = posts.count()

    context = {
        'posts': posts,
        'topics': topics,
        'posts_count': posts_count,
    }

    return render(request, 'posts/home.html', context)


def post(request, pk):
    post = Post.objects.get(id=pk)
    comments = post.comment_set.all().order_by('-created') # get the comments from each post
    comments_count = post.comment_set.all().count()

    if request.method == 'POST':
        Comment.objects.create(
            user = request.user,
            post = post,
            body = request.POST.get('comment')
        )

        messages.success(request, 'Successfully added your new comment!')

        return redirect('posts:post', pk=post.id)

    context = {
        'post': post,
        'comments': comments,
        'comments_count': comments_count,
    }

    return render(request, 'posts/post.html', context)


@login_required(login_url='user:sign-in')
def create_post(request):
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user

            post.save()

            messages.success(request, 'Successfully created your new post!')

            return redirect('posts:index')
        else:
            messages.error(request, 'Something went wrong...')


    context = {
        'form': form
    }

    return render(request, 'posts/post_form.html', context)


@login_required(login_url='user:sign-in')
def update_post(request, pk):
    post = None
    form = None
    try:
        post = Post.objects.get(id=pk)
        form = PostForm(instance=post) # get the instance of the specific post - prefill the inputs in the form

        if request.user != post.user:
            messages.error(request, 'Oops! Something went wrong...', extra_tags='danger')
            return redirect('posts:index')

        if request.method == 'POST':
            form = PostForm(request.POST, instance=post) # if instance is not specified here again, it will create a new post instead of updating
            next = request.POST.get('next', '/')

            if form.is_valid():
                form.save()

                messages.success(request, 'Successfully updated your post!')

                return HttpResponseRedirect(next)
            else:
                messages.error(request, 'Something went wrong...')
    except Post.DoesNotExist:
        messages.error(request, 'Oops! Something went wrong...', extra_tags='danger')
        return redirect('posts:index')


    context = {
        'post': post,
        'form': form,
    }

    return render(request, 'posts/post_form.html', context)


@login_required(login_url='user:sign-in')
def delete_post(request, pk):
    post = None
    try:
        post = Post.objects.get(id=pk)

        if request.user != post.user:
            messages.error(request, 'Oops! Something went wrong...', extra_tags='danger')
            return redirect('posts:index')

        if request.method == 'POST':
            post.delete()

            messages.success(request, 'Successfully deleted your post!')

            return redirect('posts:index')

    except Post.DoesNotExist:
        messages.error(request, 'Oops! Something went wrong...', extra_tags='danger')
        return redirect('posts:index')

    context = {
        'to_delete': post
    }

    return render(request, 'delete.html', context)

PAL - final project/pal/posts/templates/posts/home.html
{% extends 'main.html' %}

{% block content %}

<div class="row justify-content-md-center mt-5 mb-5">

    <div class="col-9">
        {% include 'posts/posts_component.html' %}
    </div>

    <div class="col-3">
        {% include 'posts/topics_component.html' %}
    </div>    

</div>


{% endblock content %}

PAL - final project/pal/posts/templates/posts/post.html
{% extends 'main.html' %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="editCommentModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
</div><!-- /.modal -->

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
</div><!-- /.modal -->

<div class="mt-5">
    <h1>{{ post.name }}</h3>
    <p>{{ post.description }}</p>

    {% if request.user == post.user %}
        <a href="{% url 'posts:update-post' post.id %}?next={{ request.path|urlencode }}" class="btn btn-outline-secondary" data-target="#editCommentModal">update</a>
        <a href="{% url 'posts:delete-post' post.id %}?next={{ request.path|urlencode }}" class="btn btn-outline-danger" data-target="#deleteModal">delete</a>
    {% endif %}
</div>

<hr />

<h4>Comments</h4>
{% if request.user.is_authenticated %}
    <div class="mb-3">
        <form action="" method='POST'>
            {% csrf_token %}

            <label for="formGroupExampleInput" class="form-label">Enter your comment here</label>
            <textarea name="comment" id="comment-textarea" class="form-control" cols="50" rows="5" placeholder="Enter your comment..."></textarea>

            <input type="submit" value="Add comment" class="btn btn-success">
        </form>
    </div>
{% endif %}

<div class="comment-container mt-5">
    {% if comments.count == 0 %}
        <p>No comments :(</p>
    {% endif %}


    {% for comment in comments %}

        <div class="comment">
            <p><b>@{{ comment.user }}</b> - {{ comment.created|timesince }} ago</p>
            <p>{{ comment.body }}</p>

            {% if request.user == comment.user %}
                <small>
                    <a href="{% url 'comments:update-comment' comment.id %}?next={{ request.path|urlencode }}" class="text-secondary">edit</a>
                </small>
                <small>
                    <a href="{% url 'comments:delete-comment' comment.id %}?next={{ request.path|urlencode }}" class="text-danger">delete</a>
                </small>
            {% endif %}
        </div>

    {% endfor %}
</div>

{% endblock content %}

PAL - final project/pal/posts/templates/posts/post_form.html
{% extends 'main.html' %}

{% block content %}

<div class="wrapper">
    <div class="form__container">
        <form action="" method="POST" class="form">
            {% csrf_token %}
        
            {{ form }}
        
            <input type="hidden" name="next" value="{{ request.GET.next }}">
            
            <div class="btn-container">
                <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">Cancel</a> 
                <input type="submit" value="Submit" class="btn btn-success">
            </div>
        </form>
    </div>
</div>

{% endblock content %}

PAL - final project/pal/posts/templates/posts/posts_component.html
<div class="d-flex justify-content-between align-items-center">
    <a href="{% url 'posts:create-post' %}" class="btn btn-outline-success">Create Post</a>
    
    <form method="GET" action="{% url 'posts:index' %}" class="d-flex mr-5">
        <input id="search_all_input" class="form-control me-2" name="q" type="search" placeholder="Search posts, comments, topics, users..." aria-label="Search">
        <button class="btn btn-outline-primary" type="submit">Search</button>
    </form>
</div>

{% for post in posts %}

    {% if post.topic_set.all.count == 0 %}
        <h1>No posts :(</h1>
    {% endif %}

    <div class="card mt-3">

        <div class="card-header d-flex justify-content-between align-items-center">
            <div>
                <p>Posted by <b>@{{ post.user }}</b> - {{ post.created|timesince }} ago</p>
                <small>Topic: <a href="{% url 'posts:index' %}?q={{ post.topic.name }}" class="text-muted">{{ post.topic }}</a></small>
            </div>

            {% if request.user == post.user %}
            <div>
                <a href="{% url 'posts:update-post' post.id %}?next={{ request.path|urlencode }}" class="btn btn-outline-secondary">update</a>
                <a href="{% url 'posts:delete-post' post.id %}?next={{ request.path|urlencode }}" class="btn btn-outline-danger">delete</a>
            </div>
            {% endif %}
        </div>

        <div class="card-body">
            <h5>
            <a class="card-title" href="{% url 'posts:post' post.id %}">{{ post.name }}</a>
            </h5>
            <p class="card-text">{{ post.description }}</p>
            <small class="d-block mb-1">
                <a href="{% url 'posts:post' post.id %}" class=" text-muted">{{ post.comment_set.all.count }} comments</a>
            </small>
        </div>
    </div>

{% endfor %}

PAL - final project/pal/posts/templates/posts/topics_component.html
<ul class="list-group">
    <li class="list-group-item bg-light">
        <b>Hot Topics</b>
    </li>

    <li class="list-group-item d-flex justify-content-between align-items-center">
        <a href="{% url 'posts:index' %}">ALL TOPICS</a>
        <span class="badge bg-primary rounded-pill">{{ posts_count }}</span>
    </li>

    {% for topic in topics %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <a href="{% url 'posts:index' %}?q={{ topic.name }}">{{ topic.name }}</a>
            <span class="badge bg-primary rounded-pill">{{ topic.post_set.all.count }}</span>
        </li>
    {% endfor %}
</ul>