PAL - final project/pal/pal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls')),
    path('', include('comments.urls')),
    path('', include('user.urls')),
    path('admin/', admin.site.urls),
]

PAL - final project/pal/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
  path('', views.index, name='index'),
  path('post/<str:pk>/', views.post, name='post'),
  path('create-post/', views.create_post, name='create-post'),
  path('update-post/<str:pk>/', views.update_post, name='update-post'),
  path('delete-post/<str:pk>/', views.delete_post, name='delete-post'),
]

PAL - final project/pal/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('sign-up/', views.sign_up, name='sign-up'),
    path('sign-in', views.sign_in, name='sign-in'),
    path('log-out', views.log_out, name='log-out')
]

PAL - final project/pal/templates/delete.html
{% extends 'main.html' %}

{% block content %}


<div class="modal-dialog">
    <div class="modal-content">
        <form action="" method="POST">
            <div class="modal-header">
                <h5 class="modal-title">Delete</h5>
            </div>

            <div class="modal-body">
                {% csrf_token %}
            
                <p>Are you sure you want to delete <b>"{{ to_delete }}"</b> ?</p>
            
                <input type="hidden" name="next" value={{ request.GET.next }}>
            </div>

            <div class="modal-footer">
                <a href="{{ request.META.HTTP_REFERER }}">Cancel</a>
                <input type="submit" value="Delete" class="btn btn-danger">
            </div>
        </form>
    </div>
</div>

  

{% endblock content %}

PAL - final project/pal/templates/error.html
<h1>Oops! Something went wrong...</h1>

PAL - final project/pal/templates/main.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'styles/main.css' %}">
  <title>PAL</title>
</head>
<body>
  
  {% include 'navbar.html' %}

  <div class="container">
    
  {% if messages %}
    {% for message in messages %}
      <div {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4"{% endif %} role="alert">
        <p class="m-0">{{ message }}</p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>       
    {% endfor %}
  {% endif %}
    

    {% block content %}
    {% endblock content %}
  </div>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>

PAL - final project/pal/templates/navbar.html
{% comment %} <nav class="navbar">
    <a href="{% url 'posts:index' %}" class="navbar__logo">PAL</a>

    <div class="navbar__btn-container">
        {% if request.user.is_authenticated %}
            <p>Hello, {{ request.user.username }} </p>
            <a href="{% url 'user:log-out' %}" class="navbar__btn-container--logout">Log Out</a>
        {% else %}
            <a href="{% url 'user:sign-in' %}" class="navbar__btn-container--signin">Sign in</a>
            <a href="{% url 'user:sign-up' %}" class="navbar__btn-container--signup">Sign up</a>
        {% endif %}
    </div>
    
</nav> {% endcomment %}

<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <div class="container-fluid">
      <h1 class="navbar-brand">PAL</h1>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'posts:index' %}">All Posts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:create-post' %}">Create Post</a>
          </li>
        </ul>

        <div class="d-flex align-center">
            {% if request.user.is_authenticated %}
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                        Hello, {{ request.user.username }}!
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                      <li><a class="dropdown-item" href="{% url 'user:log-out' %}">Logout</a></li>
                    </ul>
                  </div>
            {% else %}
                <div>
                    <a href="{% url 'user:sign-in' %}" class="btn btn-outline-secondary">Sign in</a>
                    <a href="{% url 'user:sign-up' %}" class="btn btn-primary">Sign up</a>
                </div>
            {% endif %}
        </div>
        
      </div>
    </div>
  </nav>

PAL - final project/pal/templates/not_allowed.html
<h1>Sorry, you are not allowed here!</h1>